AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: VPC Lambda -> DynamoDB


Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      Runtime: nodejs8.10
      CodeUri: ./
      Policies:
        - AmazonDynamoDBReadOnlyAccess
        - AWSLambdaVPCAccessExecutionRole
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue vpc-live:DefaultSecurityGroupId
        SubnetIds:
          - !ImportValue vpc-live:PrivateSubnetAId

  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.put
      Runtime: nodejs8.10
      CodeUri: ./
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaVPCAccessExecutionRole
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue vpc-live:DefaultSecurityGroupId
        SubnetIds:
          - !ImportValue vpc-live:PrivateSubnetAId

  Table:
    Type: AWS::Serverless::SimpleTable

  DynamoDBEndpoint:
     Type: AWS::EC2::VPCEndpoint
     Properties:
       RouteTableIds:
         - !ImportValue vpc-live::PrivateRouteTable
         - !ImportValue vpc-live::PublicRouteTable
       ServiceName: !Sub com.amazonaws.${AWS::Region}.dynamodb
       VpcId: !ImportValue vpc-live:VPC

Outputs:
  GetFunctionArn:
    Description: Get Function Arn
    Value: !GetAtt GetFunction.Arn
  PutFunctionArn:
    Description: Put Function Arn
    Value: !GetAtt PutFunction.Arn
  TableArn:
    Description: Table Arn
    Value: !GetAtt Table.Arn
  DynamoDBEndpointOutput:
    Description: DynamoDB VPC Endpoint
    Value: !Ref DynamoDBEndpoint
