AWSTemplateFormatVersion: 2010-09-09
Description: SNS -> Lambda
Outputs:
  BucketArn:
    Description: Bucket Arn
    Value:
      Fn::GetAtt:
      - SourceBucket
      - Arn
  SNSArn:
    Description: SNS Topic Arn
    Value:
      Fn::Sub:
      - arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${TopicName}
      - TopicName:
          Fn::GetAtt:
          - SNSTopicS3Destination
          - TopicName
Resources:
  SNSTopicS3Destination:
    Type: AWS::SNS::Topic
  SNSTopicS3DestinationPolicy:
    Properties:
      PolicyDocument:
        Id: SNSTopicS3DestinationPolicy
        Statement:
        - Action: sns:Publish
          Effect: Allow
          Principal:
            Service:
            - s3.amazonaws.com
          Resource: '*'
          Sid: AllowS3ToPut
        Version: 2012-10-17
      Topics:
      - Ref: SNSTopicS3Destination
    Type: AWS::SNS::TopicPolicy
  SourceBucket:
    Properties:
      NotificationConfiguration:
        TopicConfigurations:
        - Event: s3:ObjectCreated:*
          Topic: arn:aws:sns:us-east-1:975482786146:s3-sns-live-SNSTopicS3Destination-HZNL1VC04TN7
    Type: AWS::S3::Bucket
Transform: AWS::Serverless-2016-10-31
