AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: APIG -> Lambda

Parameters:
  Namespace:
    Type: String
    Default: live
    Description: Globally unique grouping identifier.

Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.hello
      Runtime: nodejs8.10
      CodeUri: ./
      Tracing: Active
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /hello
            Method: get

Outputs:
    ApiURL:
      Description: "API endpoint URL"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Stage/hello"

