AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Kinesis -> Lambda


Parameters:
  Namespace:
    Type: String
    Default: live
    Description: Globally unique grouping identifier.

Resources:
  StreamProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      CodeUri: ./
      Policies:
        - AWSLambdaVPCAccessExecutionRole
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt Stream.Arn
            StartingPosition: TRIM_HORIZON
      VpcConfig:
        SecurityGroupIds:
          - Fn::ImportValue: !Sub vpc-${Namespace}:DefaultSecurityGroupId
        SubnetIds:
          - Fn::ImportValue: !Sub vpc-${Namespace}:PrivateSubnetAId

  Stream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

Outputs:
  StreamProcessorArn:
    Description: Stream Processor Arn
    Value: !GetAtt StreamProcessor.Arn
  KinesisStreamArn:
    Description: Kinesis Stream Arn
    Value: !GetAtt Stream.Arn
