AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda -> DynamoDB
Outputs:
  GetFunctionArn:
    Description: Get Function Arn
    Value:
      Fn::GetAtt:
      - GetFunction
      - Arn
  PutFunctionArn:
    Description: Put Function Arn
    Value:
      Fn::GetAtt:
      - PutFunction
      - Arn
  TableArn:
    Description: Table Arn
    Value:
      Fn::GetAtt:
      - Table
      - Arn
Resources:
  GetFunction:
    Properties:
      CodeUri: s3://cz-sam-deployment-research/fe5a7994942a56000a4df7a9eb97682d
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Handler: index.get
      Policies: AmazonDynamoDBReadOnlyAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  PutFunction:
    Properties:
      CodeUri: s3://cz-sam-deployment-research/fe5a7994942a56000a4df7a9eb97682d
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
      Handler: index.put
      Policies: AmazonDynamoDBFullAccess
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  Table:
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
